name = "asn-quiz"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
APP_ORIGIN = "https://abdulkadirsezgin.github.io/asn-quiz"

[[kv_namespaces]]
binding = "QUIZ_KV"
id = "2ecc367e4299466dbf82b9a8b4629bd3"

[[durable_objects.bindings]]
name = "GAME"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

